export enum UserPermissionsEnum {
  BOD = "BOD",
  BOARD_COMMITTEES = "BOARD_COMMITTEES",
  BOARD_MEETINGS = "BOARD_MEETINGS",
  MEETING_INSIDE_THE_BOD = "MEETING_INSIDE_THE_BOD",
  COMMITTEE = "COMMITTEE",
  MEETING_INSIDE_THE_COMMITTEE = "MEETING_INSIDE_THE_COMMITTEE",
  MEETING = "MEETING",
  DECISION = "DECISION",
  RECOMMENDATION = "RECOMMENDATION",
  TASK = "TASK",
  VOTING = "VOTING",
  VOTING_SECRETARY_RESULTS = "VOTING_SECRETARY_RESULTS",
  VOTING_RESULTS = "VOTING_RESULTS",
  DRAFT_MOM = "DRAFT_MOM",
  FINAL_MOM = "FINAL_MOM",
  MOM = "MOM",
  AGENDA = "AGENDA",
  ATTENDEES = "ATTENDEES",
  COMMENT = "COMMENT"
}

export enum PermissionsActions {
  VIEW = "VIEW",
  CREATE = "CREATE",
  EDIT = "EDIT",
  DELETE = "DELETE",
  REORDER = "REORDER",
  DOWNLOAD = "DOWNLOAD",
  MARK = "MARK",
  GENERATE = "GENERATE",
  TERMINATE = "TERMINATE",
  START = "START",
  END = "END",
  ACTIVATE = "ACTIVATE"
}
